package com.lning.melireader.core.repository.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lning.melireader.core.repository.db.pojo.CollectionPojo;
import com.lning.melireader.core.repository.db.pojo.HistoryPojo;
import com.lning.melireader.core.repository.db.pojo.SearchHistory;
import com.lning.melireader.core.repository.db.pojo.TagPojo;
import com.lning.melireader.core.repository.http.bean.NewsListVo;
import com.lning.melireader.core.repository.http.bean.UserBasicVo;
import com.lning.melireader.core.repository.http.bean.UserVo;

import com.lning.melireader.core.repository.db.dao.CollectionPojoDao;
import com.lning.melireader.core.repository.db.dao.HistoryPojoDao;
import com.lning.melireader.core.repository.db.dao.SearchHistoryDao;
import com.lning.melireader.core.repository.db.dao.TagPojoDao;
import com.lning.melireader.core.repository.db.dao.NewsListVoDao;
import com.lning.melireader.core.repository.db.dao.UserBasicVoDao;
import com.lning.melireader.core.repository.db.dao.UserVoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionPojoDaoConfig;
    private final DaoConfig historyPojoDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig tagPojoDaoConfig;
    private final DaoConfig newsListVoDaoConfig;
    private final DaoConfig userBasicVoDaoConfig;
    private final DaoConfig userVoDaoConfig;

    private final CollectionPojoDao collectionPojoDao;
    private final HistoryPojoDao historyPojoDao;
    private final SearchHistoryDao searchHistoryDao;
    private final TagPojoDao tagPojoDao;
    private final NewsListVoDao newsListVoDao;
    private final UserBasicVoDao userBasicVoDao;
    private final UserVoDao userVoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionPojoDaoConfig = daoConfigMap.get(CollectionPojoDao.class).clone();
        collectionPojoDaoConfig.initIdentityScope(type);

        historyPojoDaoConfig = daoConfigMap.get(HistoryPojoDao.class).clone();
        historyPojoDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        tagPojoDaoConfig = daoConfigMap.get(TagPojoDao.class).clone();
        tagPojoDaoConfig.initIdentityScope(type);

        newsListVoDaoConfig = daoConfigMap.get(NewsListVoDao.class).clone();
        newsListVoDaoConfig.initIdentityScope(type);

        userBasicVoDaoConfig = daoConfigMap.get(UserBasicVoDao.class).clone();
        userBasicVoDaoConfig.initIdentityScope(type);

        userVoDaoConfig = daoConfigMap.get(UserVoDao.class).clone();
        userVoDaoConfig.initIdentityScope(type);

        collectionPojoDao = new CollectionPojoDao(collectionPojoDaoConfig, this);
        historyPojoDao = new HistoryPojoDao(historyPojoDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        tagPojoDao = new TagPojoDao(tagPojoDaoConfig, this);
        newsListVoDao = new NewsListVoDao(newsListVoDaoConfig, this);
        userBasicVoDao = new UserBasicVoDao(userBasicVoDaoConfig, this);
        userVoDao = new UserVoDao(userVoDaoConfig, this);

        registerDao(CollectionPojo.class, collectionPojoDao);
        registerDao(HistoryPojo.class, historyPojoDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(TagPojo.class, tagPojoDao);
        registerDao(NewsListVo.class, newsListVoDao);
        registerDao(UserBasicVo.class, userBasicVoDao);
        registerDao(UserVo.class, userVoDao);
    }
    
    public void clear() {
        collectionPojoDaoConfig.clearIdentityScope();
        historyPojoDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        tagPojoDaoConfig.clearIdentityScope();
        newsListVoDaoConfig.clearIdentityScope();
        userBasicVoDaoConfig.clearIdentityScope();
        userVoDaoConfig.clearIdentityScope();
    }

    public CollectionPojoDao getCollectionPojoDao() {
        return collectionPojoDao;
    }

    public HistoryPojoDao getHistoryPojoDao() {
        return historyPojoDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public TagPojoDao getTagPojoDao() {
        return tagPojoDao;
    }

    public NewsListVoDao getNewsListVoDao() {
        return newsListVoDao;
    }

    public UserBasicVoDao getUserBasicVoDao() {
        return userBasicVoDao;
    }

    public UserVoDao getUserVoDao() {
        return userVoDao;
    }

}
