package com.lning.melireader.core.repository.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lning.melireader.core.repository.db.converter.DateConverter;
import java.util.Date;

import com.lning.melireader.core.repository.db.pojo.TagPojo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TAG_POJO".
*/
public class TagPojoDao extends AbstractDao<TagPojo, Long> {

    public static final String TABLENAME = "TAG_POJO";

    /**
     * Properties of entity TagPojo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Created = new Property(3, Long.class, "created", false, "CREATED");
    }

    private final DateConverter createdConverter = new DateConverter();

    public TagPojoDao(DaoConfig config) {
        super(config);
    }
    
    public TagPojoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAG_POJO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" TEXT NOT NULL ," + // 1: userId
                "\"CONTENT\" TEXT NOT NULL ," + // 2: content
                "\"CREATED\" INTEGER);"); // 3: created
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAG_POJO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TagPojo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUserId());
        stmt.bindString(3, entity.getContent());
 
        Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(4, createdConverter.convertToDatabaseValue(created));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TagPojo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUserId());
        stmt.bindString(3, entity.getContent());
 
        Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(4, createdConverter.convertToDatabaseValue(created));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TagPojo readEntity(Cursor cursor, int offset) {
        TagPojo entity = new TagPojo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // userId
            cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : createdConverter.convertToEntityProperty(cursor.getLong(offset + 3)) // created
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TagPojo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getString(offset + 1));
        entity.setContent(cursor.getString(offset + 2));
        entity.setCreated(cursor.isNull(offset + 3) ? null : createdConverter.convertToEntityProperty(cursor.getLong(offset + 3)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TagPojo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TagPojo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TagPojo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
