package com.lning.melireader.core.repository.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lning.melireader.core.repository.db.converter.UserItemListConverter;
import com.lning.melireader.core.repository.http.bean.ItemListVo;

import com.lning.melireader.core.repository.http.bean.UserBasicVo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_BASIC_VO".
*/
public class UserBasicVoDao extends AbstractDao<UserBasicVo, String> {

    public static final String TABLENAME = "USER_BASIC_VO";

    /**
     * Properties of entity UserBasicVo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Rid = new Property(1, Long.class, "rid", false, "RID");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
        public final static Property Nickname = new Property(3, String.class, "nickname", false, "NICKNAME");
        public final static Property Profile = new Property(4, String.class, "profile", false, "PROFILE");
        public final static Property Experience = new Property(5, int.class, "experience", false, "EXPERIENCE");
        public final static Property AttentionCount = new Property(6, int.class, "attentionCount", false, "ATTENTION_COUNT");
        public final static Property FansCount = new Property(7, int.class, "fansCount", false, "FANS_COUNT");
        public final static Property Level = new Property(8, int.class, "level", false, "LEVEL");
        public final static Property UpperLimit = new Property(9, int.class, "upperLimit", false, "UPPER_LIMIT");
        public final static Property LevelName = new Property(10, String.class, "levelName", false, "LEVEL_NAME");
        public final static Property ItemListVo = new Property(11, String.class, "itemListVo", false, "ITEM_LIST_VO");
        public final static Property Type = new Property(12, String.class, "type", false, "TYPE");
        public final static Property Token = new Property(13, String.class, "token", false, "TOKEN");
        public final static Property FavouriteChannels = new Property(14, String.class, "favouriteChannels", false, "FAVOURITE_CHANNELS");
        public final static Property Subscripted = new Property(15, boolean.class, "subscripted", false, "SUBSCRIPTED");
    }

    private final UserItemListConverter itemListVoConverter = new UserItemListConverter();

    public UserBasicVoDao(DaoConfig config) {
        super(config);
    }
    
    public UserBasicVoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_BASIC_VO\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"RID\" INTEGER NOT NULL ," + // 1: rid
                "\"USERNAME\" TEXT NOT NULL ," + // 2: username
                "\"NICKNAME\" TEXT NOT NULL ," + // 3: nickname
                "\"PROFILE\" TEXT NOT NULL ," + // 4: profile
                "\"EXPERIENCE\" INTEGER NOT NULL ," + // 5: experience
                "\"ATTENTION_COUNT\" INTEGER NOT NULL ," + // 6: attentionCount
                "\"FANS_COUNT\" INTEGER NOT NULL ," + // 7: fansCount
                "\"LEVEL\" INTEGER NOT NULL ," + // 8: level
                "\"UPPER_LIMIT\" INTEGER NOT NULL ," + // 9: upperLimit
                "\"LEVEL_NAME\" TEXT," + // 10: levelName
                "\"ITEM_LIST_VO\" TEXT," + // 11: itemListVo
                "\"TYPE\" TEXT NOT NULL ," + // 12: type
                "\"TOKEN\" TEXT NOT NULL ," + // 13: token
                "\"FAVOURITE_CHANNELS\" TEXT NOT NULL ," + // 14: favouriteChannels
                "\"SUBSCRIPTED\" INTEGER NOT NULL );"); // 15: subscripted
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_BASIC_VO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserBasicVo entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getRid());
        stmt.bindString(3, entity.getUsername());
        stmt.bindString(4, entity.getNickname());
        stmt.bindString(5, entity.getProfile());
        stmt.bindLong(6, entity.getExperience());
        stmt.bindLong(7, entity.getAttentionCount());
        stmt.bindLong(8, entity.getFansCount());
        stmt.bindLong(9, entity.getLevel());
        stmt.bindLong(10, entity.getUpperLimit());
 
        String levelName = entity.getLevelName();
        if (levelName != null) {
            stmt.bindString(11, levelName);
        }
 
        ItemListVo itemListVo = entity.getItemListVo();
        if (itemListVo != null) {
            stmt.bindString(12, itemListVoConverter.convertToDatabaseValue(itemListVo));
        }
        stmt.bindString(13, entity.getType());
        stmt.bindString(14, entity.getToken());
        stmt.bindString(15, entity.getFavouriteChannels());
        stmt.bindLong(16, entity.getSubscripted() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserBasicVo entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getRid());
        stmt.bindString(3, entity.getUsername());
        stmt.bindString(4, entity.getNickname());
        stmt.bindString(5, entity.getProfile());
        stmt.bindLong(6, entity.getExperience());
        stmt.bindLong(7, entity.getAttentionCount());
        stmt.bindLong(8, entity.getFansCount());
        stmt.bindLong(9, entity.getLevel());
        stmt.bindLong(10, entity.getUpperLimit());
 
        String levelName = entity.getLevelName();
        if (levelName != null) {
            stmt.bindString(11, levelName);
        }
 
        ItemListVo itemListVo = entity.getItemListVo();
        if (itemListVo != null) {
            stmt.bindString(12, itemListVoConverter.convertToDatabaseValue(itemListVo));
        }
        stmt.bindString(13, entity.getType());
        stmt.bindString(14, entity.getToken());
        stmt.bindString(15, entity.getFavouriteChannels());
        stmt.bindLong(16, entity.getSubscripted() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public UserBasicVo readEntity(Cursor cursor, int offset) {
        UserBasicVo entity = new UserBasicVo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getLong(offset + 1), // rid
            cursor.getString(offset + 2), // username
            cursor.getString(offset + 3), // nickname
            cursor.getString(offset + 4), // profile
            cursor.getInt(offset + 5), // experience
            cursor.getInt(offset + 6), // attentionCount
            cursor.getInt(offset + 7), // fansCount
            cursor.getInt(offset + 8), // level
            cursor.getInt(offset + 9), // upperLimit
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // levelName
            cursor.isNull(offset + 11) ? null : itemListVoConverter.convertToEntityProperty(cursor.getString(offset + 11)), // itemListVo
            cursor.getString(offset + 12), // type
            cursor.getString(offset + 13), // token
            cursor.getString(offset + 14), // favouriteChannels
            cursor.getShort(offset + 15) != 0 // subscripted
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserBasicVo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setRid(cursor.getLong(offset + 1));
        entity.setUsername(cursor.getString(offset + 2));
        entity.setNickname(cursor.getString(offset + 3));
        entity.setProfile(cursor.getString(offset + 4));
        entity.setExperience(cursor.getInt(offset + 5));
        entity.setAttentionCount(cursor.getInt(offset + 6));
        entity.setFansCount(cursor.getInt(offset + 7));
        entity.setLevel(cursor.getInt(offset + 8));
        entity.setUpperLimit(cursor.getInt(offset + 9));
        entity.setLevelName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setItemListVo(cursor.isNull(offset + 11) ? null : itemListVoConverter.convertToEntityProperty(cursor.getString(offset + 11)));
        entity.setType(cursor.getString(offset + 12));
        entity.setToken(cursor.getString(offset + 13));
        entity.setFavouriteChannels(cursor.getString(offset + 14));
        entity.setSubscripted(cursor.getShort(offset + 15) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(UserBasicVo entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(UserBasicVo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserBasicVo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
